management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    #hostname: localhost
    hostname: config-client
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}




