management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    hostname: localhost
    #hostname: configuration
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/







