spring:
  application:
    name: yoke-notify
  profiles:
    active: dev

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: '{cipher}a891291dc7c7254c953e62d6ddab4481a01b72641667712c5058f880b7541478'
      #password: example
      database: yoke

server:
  port: 8082